name: accept

on:
  pull_request:
    types: [review_requested]
  workflow_run:
    workflows: [build]
    types: [completed]

jobs:
  accept:
    runs-on: ubuntu-latest
    steps:
    - uses: exivity/actions/accept@main
      with:
        gh-token: ${{ secrets.GH_BOT_TOKEN }}


