name: accept

on:
  pull_request:
    types: [review_requested]
  check_run:
    types: [completed]
  status:
  push:
    branches: [develop]

jobs:
  accept:
    runs-on: ubuntu-latest

    steps:
    - name: trigger scaffold
      uses: exivity/actions/accept@master
      with:
        need-check: build
        gh-token: ${{ secrets.GH_BOT_TOKEN }}


