name: build

on: [push]

jobs:
  build:
    env:
      DB_BRANCH: develop
      TESTBENCH_BRANCH: master
      BUNNY_BRANCH: master
  
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: "1.17"

      - uses: exivity/actions/init-ssh@main
        with:
          private-key: ${{ secrets.PRIVATE_KEY }}

      - uses: exivity/actions/rabbitmq@main

      - uses: exivity/actions/db@main
        with:
          branch: ${{ env.DB_BRANCH }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          gh-token: ${{ secrets.GH_BOT_TOKEN }}

      - uses: exivity/actions/get-artefacts@main
        with:
          component: testbench
          branch: ${{ env.TESTBENCH_BRANCH }}
          use-platform-prefix: true
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          gh-token: ${{ secrets.GH_BOT_TOKEN }}

      - uses: exivity/actions/get-artefacts@main
        with:
          component: bunny
          branch: ${{ env.BUNNY_BRANCH }}
          use-platform-prefix: true
          prefix: tools
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          gh-token: ${{ secrets.GH_BOT_TOKEN }}

      - name: build
        run: go build -o build/
          
      - uses: exivity/actions/process-binary@main
        with:
          path: build/*
          certificate-base64: ${{ secrets.CODESIGN_CERTIFICATE_BASE64 }}
          certificate-password: ${{ secrets.CODESIGN_CERTIFICATE_PASSWORD }}
          virustotal-api-key: ${{ secrets.VIRUSTOTAL_API_KEY }}
          gh-token: ${{ secrets.GITHUB_TOKEN }}

      - name: test
        run: bash run-tests.sh
        working-directory: tests
        env:
          EXIVITY_HOME_PATH: ${{ github.workspace }}/tests/home
          EXIVITY_PROGRAM_PATH: ${{ github.workspace }}/tests/programs
          
      - name: copy static files
        run: cp THIRD_PARTY_LICENSES.md build

      - uses: exivity/actions/put-artefacts@main
        with:
          use-platform-prefix: true
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: build
          
      - uses: exivity/actions/slack@main
        if: failure()
        with:
          status: ${{ job.status }}
          slack-api-token: ${{ secrets.SLACK_BOT_TOKEN }}
          gh-token: ${{ secrets.GITHUB_TOKEN }}
