name: Scaffold Deployment

on:
  pull_request:
    types: [review_requested]

env:
  GITHUB_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
  SCAFFOLD_BRANCH: feat/accept-on-review

jobs:
  accept:
    runs-on: ubuntu-latest

    steps:
    - name: trigger scaffold
      if: contains(github.event.pull_request.requested_reviewers.*.id, 53756225)
      uses: exivity/actions/accept@feat/accept-on-review
      with:
        scaffold-branch: ${{ env.SCAFFOLD_BRANCH }}
    
    - name: request changes
      if: failure()
      uses: exivity/actions/bot-review@feat/accept-on-review
      with:
        event: REQUEST_CHANGES
        body: failed to trigger scaffold
