name: virustotal-check

on:
  workflow_dispatch:
  schedule:
    - cron: '45 3 * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: exivity/actions/virustotal@main
        with:
          mode: check
          virustotal-api-key: ${{ secrets.VIRUSTOTAL_API_KEY }}
          gh-token: ${{ secrets.GITHUB_TOKEN }}
